# Generated by Django 4.1.7 on 2023-05-12 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_offering_currency_offering_offeringtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='offering',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 12)),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
