# Generated by Django 4.1.7 on 2023-05-29 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_offering_currency_offering_date_alter_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 29)),
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=15)),
                ('subgroup', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.church'),
        ),
    ]
