# Generated by Django 4.1.7 on 2023-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='currency',
        ),
        migrations.AddField(
            model_name='offering',
            name='offeringType',
            field=models.CharField(default='General', max_length=15),
        ),
    ]
