# Generated by Django 4.1.7 on 2023-05-30 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_offering_date_church_member_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
    ]
